# 四足机器人的配置文件
# 第三代连杆参数

# 基类配置文件路径，不含'/'字符
# 派生类与基类配置文件的简单规则如下
# 1，派生类修改基类的某个选项，派生类中对应层级位置修改
# 2，派生类增加配置某配置选项，派生类中直接填写添加
# 3，派生类删除基类某配置选项，派生类中对应层级位置对该配置写一个空值
include = "00-base.toml"

devModel = "qr-linkV2-3" # 设备型号不变
ctrModel = "qr-gazebo"   # 四足算法型号

#------------------------------------------------------------
# 模型测试参数
#------------------------------------------------------------
enableParam = true
printInfo = false

# 模型文件路径
# format: ./onnx_model/{模型生成日期}/{当日模型序号}/nvidia_result_{模型节点}.onnx
onnxPath.normal = "./onnx_model/sz/normalMode/2024-10-09-09:44:25-best.onnx" # 0.75 -1.5
onnxPath.climb = "./onnx_model/sz/climbMode/nvidia_result_2000.onnx"
onnxPath.handstand = "./onnx_model/sz/handStandMode/2024-12-05-13:44:33-9950.onnx"
onnxPath.upright = "./onnx_model/sz/uprightMode/2025-02-11-09:38:45-2.onnx" # 实物待测试
# onnxPath.upright = "./onnx_model/sz/uprightMode/2025-01-14-20:12:29-99.onnx" # hip关节活动幅度过大
# onnxPath.upright = "./onnx_model/sz/uprightMode/2025-01-14-20:14:43-99.onnx" # 实物可测试，直线倒退偏移，转弯前进尚可

kp.nml_clb = 25.0
kd.nml_clb = 0.8
kp.handstand = 25.0 # 关节kp系数。若数组长度为1，则所有关节使用相同kp；若数组长度为12，则对应关节使用对应系数
kd.handstand = 0.8  # 关节kd系数。若数组长度为1，则所有关节使用相同kp；若数组长度为12，则对应关节使用对应系数
kp.upright = 35.0   # 关节kp系数。若数组长度为1，则所有关节使用相同kp；若数组长度为12，则对应关节使用对应系数
kd.upright = 1.0    # 关节kd系数。若数组长度为1，则所有关节使用相同kp；若数组长度为12，则对应关节使用对应系数

kFilter.normal = 0.6 # 滤波系数
kFilter.climb = 0.6 # 滤波系数
kFilter.handstand = 1.0
kFilter.upright = 0.8
defaultJoints.normal = [
    0.0, 0.9, -1.8,
    0.0, 0.9, -1.8,
    0.0, 0.9, -1.8,
    0.0, 0.9, -1.8,
]
defaultJoints.climb = [
    0.0, 0.9, -1.8,
    0.0, 0.9, -1.8,
    0.0, 0.9, -1.8,
    0.0, 0.9, -1.8,
]
defaultJoints.handstand = [
    0.0, 0.7, -2.05,
    0.0, 0.7, -2.05,
    0.0, 1.15, -1.75,
    0.0, 1.15, -1.75,
]
defaultJoints.upright = [
    0.0, 0.9, -1.8, # 0.0, 1.9, -1.2,
    0.0, 0.9, -1.8, # 0.0, 1.9, -1.2,
    0.0, 0.9, -1.8, # 0.0, 2.43, -1.74,
    0.0, 0.9, -1.8, # 0.0, 2.43, -1.74,
]

defaultHip = 0.0   # 默认hip关节角度
defaultThigh = 0.9 # 默认thigh关节角度
defaultCalf = -1.8 # 默认calf关节角度

aiActionScale = 0.25 # AI动作的缩放比例
#------------------------------------------------------------
