# 四足机器人的配置文件
# 第三代连杆参数

# 基类配置文件路径，不含'/'字符
# 派生类与基类配置文件的简单规则如下
# 1，派生类修改基类的某个选项，派生类中对应层级位置修改
# 2，派生类增加配置某配置选项，派生类中直接填写添加
# 3，派生类删除基类某配置选项，派生类中对应层级位置对该配置写一个空值
include = "00-base.toml"

devModel = "qr-linkV2-3-w" # 设备型号不变
ctrModel = "qr-gazebo-w"   # 四足算法型号

#------------------------------------------------------------
# 模型测试参数
#------------------------------------------------------------
enableParam = true
printInfo = false

# 模型文件路径
# format: ./onnx_model/{模型生成日期}/{当日模型序号}/nvidia_result_{模型节点}.onnx
onnxPath.climb = "./onnx_model/sz_wheel/2025-04-30-16:29:55-1.onnx"     # 
onnxPath.normal = "./onnx_model/sz_wheel/2025-04-30-16:29:55-1.onnx"
onnxPath.upright = "./onnx_model/sz_wheel/2025-04-30-16:29:55-1.onnx"
onnxPath.handstand = "./onnx_model/sz_wheel/2025-04-30-16:29:55-1.onnx"

kFilter.climb = 0.6     # 滤波系数
kFilter.normal = 0.6    # 滤波系数
kFilter.upright = 0.6   # 滤波系数
kFilter.handstand = 0.6 # 滤波系数

kp.nml_clb = [
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0
]
kd.nml_clb = [
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5
]
kp.upright = [
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0
]
kd.upright = [
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5
]
kp.handstand = [
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0,
    45.0, 45.0, 45.0, 0.0
]
kd.handstand = [
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5,
    1.2, 1.2, 1.2, 0.5
]

defaultJoints.climb = [
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
]
defaultJoints.normal = [
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
]
defaultJoints.upright = [
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
]
defaultJoints.handstand = [
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
    -0.05, 0.9, -1.8, 0.0, 
     0.05, 0.9, -1.8, 0.0, 
]

aiActionScale = 0.25 # AI动作的缩放比例
#------------------------------------------------------------
