# 四足机器人的配置文件
# 第三代连杆参数

# 基类配置文件路径，不含'/'字符
# 派生类与基类配置文件的简单规则如下
# 1，派生类修改基类的某个选项，派生类中对应层级位置修改
# 2，派生类增加配置某配置选项，派生类中直接填写添加
# 3，派生类删除基类某配置选项，派生类中对应层级位置对该配置写一个空值
include = "00-base.toml"

devModel = "qr-linkV2-3" # 设备型号不变
ctrModel = "qr-middleV4" # 四足算法型号

#armModel = "arm"
